/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gajenje_ovaca.gui.dnevnik;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ScrollPaneLayout;
import org.jdesktop.layout.GroupLayout;

/**
 *
 * @author ivantadic
 */
public class DnavniKalendarPanel extends JPanel{
    private static int TOP_MARGIN = 0;
    /**
     * Creates new form DnavniKalendarPanel
     */
    public DnavniKalendarPanel() {
        //initComponents();
        setLayout(new GroupLayout(this));
        add(new JLabel("label 2323232"));
        repaint();
        //this.setLayout(new FlowLayout());
        setBackground(Color.WHITE);
        addMouseCapability();
    }
    

    public void addMouseCapability(){
        addMouseListener(new MouseAdapter() {
                private Color background;

                @Override
                public void mousePressed(MouseEvent e) {
                    //JPanel eventPanel = new JPanel();
                    //eventPanel.setPreferredSize(new Dimension(200, 50));
                    //eventPanel.setVisible(true);
                    setLayout(new FlowLayout());
                    add(new JLabel("label 2323232"),0);
            
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                   // setBackground(background);
                }
            });  
    }


    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.setFont(new Font("Arial", Font.BOLD, 14));
        for (int i=0; i<=24; i++){
            g.setColor(new Color(202, 202, 202));
            g.drawString(getTimeString(i), 10, TOP_MARGIN + i*64);
            
            g.drawLine(55, TOP_MARGIN + (i*64)-5, 450, TOP_MARGIN + (i*64)-5);
            g.setColor(new Color(230, 227, 227));
            g.drawLine(55, TOP_MARGIN + (i*64)+27, 450, TOP_MARGIN + (i*64)+27);
        }
        repaint();
    }
    
    private String getTimeString(int i){
        StringBuilder sb = new StringBuilder();
        if (i<10){
            sb.append('0');
        }
        sb.append(Integer.toString(i));
        sb.append(":00");
        return sb.toString();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1532, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
