/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gajenje_ovaca;

import app.logic.Logic;
import app.model.Ovca;
import com.apple.laf.AquaTextFieldBorder;
import com.toedter.components.JTitlePanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author ivantadic
 */
public class OvcaPrikaz extends javax.swing.JPanel {
    private Ovca ovca;
    private Logic logic;
    private JPanel mainPanel;

    /**
     * Creates new form Podaci_ovaca
     */
    public OvcaPrikaz(JPanel mainpanel, Logic logic, Ovca o) {
        this.logic = logic;
        this.ovca = o;
        this.mainPanel = mainpanel;
        initComponents();
        jScrollPane1.getViewport().setBackground(Color.white);

        setBoldFontToColumn(3);
        
        setSheepToPanel(o);
    }
    
    private void setTitleToPanel(JPanel panel, String title){
        TitledBorder tb = new TitledBorder(title);
        tb.setTitleFont(new Font("Noteworthy", Font.BOLD, 18));
        tb.setTitleColor(Color.red.darker());
        panel.setBorder(tb); 
    }

    private void setSheepToPanel(Ovca o){
        setTitleToPanel(jPanelOpstipodatci, "Grlo " + o.getNadimak() + " - " + o.getOznaka() + " -");
        if (o.getPol()=='m'){
            jPol.setSelectedIndex(0);
        } else {
            jPol.setSelectedIndex(1);
        }
        jProcenatR.setText(Float.toString(o.getProcenatR()));
        jStatus.setText(o.getStatus());
        jOpis.setText(o.getOpis());
        jDosije.setText(o.getPracenje());
        
        setTitleToPanel(jPanelRodjenje, "Rođenje " + o.getDatumRodjenja() + " -  -");
        jOtac.setText(o.getOtac().getOznaka());
        jMajka.setText(o.getMajka().getOznaka());
        jRodjenjeNapomena.setText(o.getNabavka().getNapomena());
        jLeglo.setText(o.getLeglo().toString());
        
         setTitleToPanel(jPanelNabavka, "Nabavka " + o.getNabavka().getAktivnost().getDan().toString() + " - " + o.getNabavka().getAktivnost().getLokacija() + " -");
         jCenaNabavke.setText(Float.toString(o.getNabavka().getCena()));
         jDetaljiNabavke.setText(o.getNabavka().getNapomena());
        
    }
    
    
    private void setBoldFontToColumn(int n){
        DefaultTableCellRenderer r = new DefaultTableCellRenderer() {
            Font f = new Font ("Monaco", Font.BOLD, 16);

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus,
                    row, column);
                setFont(f);
                return this;
            }
        
        };
        jTable1.getColumnModel().getColumn(n).setCellRenderer(r);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanelRodjenje = new javax.swing.JPanel();
        jTezina = new javax.swing.JTextField();
        jLeglo = new javax.swing.JTextField();
        jMajka = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jRodjenjeNapomena = new javax.swing.JTextField();
        jOtac = new javax.swing.JTextField();
        jTezina1 = new javax.swing.JTextField();
        jPanelNabavka = new javax.swing.JPanel();
        jCenaNabavke = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jDetaljiNabavke = new javax.swing.JTextField();
        jCenaNabavke1 = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jDosije = new javax.swing.JTextArea();
        jPanelOpstipodatci = new javax.swing.JPanel();
        jStatus = new javax.swing.JTextField();
        jProcenatR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPol = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jOpis = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLinija = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable18 = new javax.swing.JTable();
        jPanel24 = new javax.swing.JPanel();
        jOznaka8 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jStatus10 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jOznaka9 = new javax.swing.JTextField();
        jCenaNabavke2 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jOznaka7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPDFSnimiButton = new javax.swing.JButton();
        jOtkaziButton = new javax.swing.JButton();
        jIzmeniButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelRodjenje.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRodjenje.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Rođenje 24-12-2014 selo Korićani", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N

        jTezina.setEditable(false);
        jTezina.setFont(new java.awt.Font("Damascus", 0, 14)); // NOI18N
        jTezina.setForeground(new java.awt.Color(0, 0, 153));
        jTezina.setText("    ");
        jTezina.setBorder(null);
        jTezina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTezinaActionPerformed(evt);
            }
        });

        jLeglo.setEditable(false);
        jLeglo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLeglo.setForeground(new java.awt.Color(0, 0, 153));
        jLeglo.setText("2");
        jLeglo.setBorder(null);
        jLeglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLegloActionPerformed(evt);
            }
        });

        jMajka.setEditable(false);
        jMajka.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMajka.setForeground(new java.awt.Color(0, 0, 153));
        jMajka.setText("6666777777");
        jMajka.setBorder(null);
        jMajka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMajkaActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setText("Težina");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setText("Otac");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel22.setText("Iz legla od");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setText("Majka");

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel24.setText("Napomena");

        jRodjenjeNapomena.setEditable(false);
        jRodjenjeNapomena.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRodjenjeNapomena.setForeground(new java.awt.Color(0, 0, 153));
        jRodjenjeNapomena.setText("napomena");
        jRodjenjeNapomena.setBorder(null);
        jRodjenjeNapomena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRodjenjeNapomenaActionPerformed(evt);
            }
        });

        jOtac.setEditable(false);
        jOtac.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jOtac.setForeground(new java.awt.Color(0, 0, 153));
        jOtac.setText("000000000");
        jOtac.setBorder(null);
        jOtac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOtacActionPerformed(evt);
            }
        });

        jTezina1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTezina1.setForeground(new java.awt.Color(0, 0, 153));
        jTezina1.setText("kg");
        jTezina1.setBorder(null);
        jTezina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTezina1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelRodjenjeLayout = new org.jdesktop.layout.GroupLayout(jPanelRodjenje);
        jPanelRodjenje.setLayout(jPanelRodjenjeLayout);
        jPanelRodjenjeLayout.setHorizontalGroup(
            jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelRodjenjeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelRodjenjeLayout.createSequentialGroup()
                        .add(jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel22, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(6, 6, 6)
                        .add(jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelRodjenjeLayout.createSequentialGroup()
                                .add(jMajka)
                                .add(31, 31, 31))
                            .add(jPanelRodjenjeLayout.createSequentialGroup()
                                .add(jLeglo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel21, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel20, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jOtac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanelRodjenjeLayout.createSequentialGroup()
                                .add(jTezina, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTezina1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanelRodjenjeLayout.createSequentialGroup()
                        .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRodjenjeNapomena)))
                .addContainerGap())
        );
        jPanelRodjenjeLayout.setVerticalGroup(
            jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelRodjenjeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jMajka, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jOtac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLeglo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTezina, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTezina1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelRodjenjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jRodjenjeNapomena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, Short.MAX_VALUE))
        );

        jPanelNabavka.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNabavka.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Nabavljena 24-12-2014 s. Korićani", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N

        jCenaNabavke.setEditable(false);
        jCenaNabavke.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCenaNabavke.setForeground(new java.awt.Color(0, 0, 153));
        jCenaNabavke.setBorder(null);
        jCenaNabavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCenaNabavkeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Cena");

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel25.setText("Detalji nabavke");

        jDetaljiNabavke.setEditable(false);
        jDetaljiNabavke.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jDetaljiNabavke.setForeground(new java.awt.Color(0, 0, 153));
        jDetaljiNabavke.setText("jTextField1");
        jDetaljiNabavke.setBorder(null);
        jDetaljiNabavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDetaljiNabavkeActionPerformed(evt);
            }
        });

        jCenaNabavke1.setEditable(false);
        jCenaNabavke1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCenaNabavke1.setForeground(new java.awt.Color(0, 0, 153));
        jCenaNabavke1.setText("€");
        jCenaNabavke1.setBorder(null);
        jCenaNabavke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCenaNabavke1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelNabavkaLayout = new org.jdesktop.layout.GroupLayout(jPanelNabavka);
        jPanelNabavka.setLayout(jPanelNabavkaLayout);
        jPanelNabavkaLayout.setHorizontalGroup(
            jPanelNabavkaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNabavkaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelNabavkaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelNabavkaLayout.createSequentialGroup()
                        .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCenaNabavke, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCenaNabavke1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanelNabavkaLayout.createSequentialGroup()
                        .add(jLabel25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jDetaljiNabavke)))
                .addContainerGap())
        );
        jPanelNabavkaLayout.setVerticalGroup(
            jPanelNabavkaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNabavkaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelNabavkaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCenaNabavke, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCenaNabavke1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNabavkaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jDetaljiNabavke, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, Short.MAX_VALUE))
        );

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Dosije", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N

        jDosije.setEditable(false);
        jDosije.setColumns(20);
        jDosije.setFont(new java.awt.Font("Osaka", 0, 14)); // NOI18N
        jDosije.setForeground(new java.awt.Color(0, 0, 153));
        jDosije.setRows(5);
        jScrollPane19.setViewportView(jDosije);

        org.jdesktop.layout.GroupLayout jPanel25Layout = new org.jdesktop.layout.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane19)
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel25Layout.createSequentialGroup()
                .add(jScrollPane19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        jPanelOpstipodatci.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpstipodatci.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Grlo \"Veselinka\"  - 99870765", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N

        jStatus.setEditable(false);
        jStatus.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jStatus.setForeground(new java.awt.Color(0, 0, 153));
        jStatus.setText("Na farmi");
        jStatus.setActionCommand("<Not Set>");
        jStatus.setAlignmentX(0.0F);
        jStatus.setAlignmentY(0.0F);
        jStatus.setBorder(null);
        jStatus.setMinimumSize(new java.awt.Dimension(0, 16));
        jStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStatusActionPerformed(evt);
            }
        });

        jProcenatR.setEditable(false);
        jProcenatR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jProcenatR.setForeground(new java.awt.Color(0, 0, 153));
        jProcenatR.setBorder(null);
        jProcenatR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProcenatRActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Status:");

        jPol.setBackground(new java.awt.Color(255, 255, 255));
        jPol.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPol.setForeground(new java.awt.Color(0, 0, 153));
        jPol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "muško", "žensko" }));
        jPol.setEnabled(false);
        jPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPolActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("proc. R:");

        jOpis.setEditable(false);
        jOpis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jOpis.setForeground(new java.awt.Color(0, 0, 153));
        jOpis.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jOpis.setText("malo crno sa belom desnom carrrrgggrapom");
        jOpis.setBorder(null);
        jOpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpisActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Opis grla:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Linija:");

        jLinija.setEditable(false);
        jLinija.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLinija.setForeground(new java.awt.Color(0, 0, 153));
        jLinija.setBorder(null);
        jLinija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinijaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("%");

        org.jdesktop.layout.GroupLayout jPanelOpstipodatciLayout = new org.jdesktop.layout.GroupLayout(jPanelOpstipodatci);
        jPanelOpstipodatci.setLayout(jPanelOpstipodatciLayout);
        jPanelOpstipodatciLayout.setHorizontalGroup(
            jPanelOpstipodatciLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOpstipodatciLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelOpstipodatciLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelOpstipodatciLayout.createSequentialGroup()
                        .add(jPanelOpstipodatciLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel14)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelOpstipodatciLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelOpstipodatciLayout.createSequentialGroup()
                                .add(jStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(jOpis, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                    .add(jPanelOpstipodatciLayout.createSequentialGroup()
                        .add(jPol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jProcenatR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLinija)))
                .addContainerGap())
        );
        jPanelOpstipodatciLayout.setVerticalGroup(
            jPanelOpstipodatciLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOpstipodatciLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelOpstipodatciLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jPol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLinija, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jProcenatR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelOpstipodatciLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelOpstipodatciLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jOpis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jagnjenja (2)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N

        jTable1.setFont(new java.awt.Font("Damascus", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Redovna vakcinacija (5)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.setEnabled(false);
        jScrollPane5.setViewportView(jTable5);

        org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lečenja (1)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N

        jTable18.setFont(new java.awt.Font("Damascus", 0, 14)); // NOI18N
        jTable18.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable18.setEnabled(false);
        jScrollPane18.setViewportView(jTable18);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prodata 25-09-2015", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel24.setEnabled(false);

        jOznaka8.setEditable(false);
        jOznaka8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jOznaka8.setForeground(new java.awt.Color(0, 0, 153));
        jOznaka8.setText("jTextField1");
        jOznaka8.setBorder(null);
        jOznaka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOznaka8ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel28.setText("Kome");

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel29.setText("Cena");

        jStatus10.setEditable(false);
        jStatus10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jStatus10.setForeground(new java.awt.Color(0, 0, 153));
        jStatus10.setBorder(null);
        jStatus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStatus10ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel30.setText("Detalji prodaje");

        jOznaka9.setEditable(false);
        jOznaka9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jOznaka9.setForeground(new java.awt.Color(0, 0, 153));
        jOznaka9.setText("jTextField1");
        jOznaka9.setBorder(null);
        jOznaka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOznaka9ActionPerformed(evt);
            }
        });

        jCenaNabavke2.setEditable(false);
        jCenaNabavke2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCenaNabavke2.setForeground(new java.awt.Color(0, 0, 153));
        jCenaNabavke2.setText("€");
        jCenaNabavke2.setBorder(null);
        jCenaNabavke2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCenaNabavke2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel24Layout = new org.jdesktop.layout.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel24Layout.createSequentialGroup()
                        .add(jLabel30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jOznaka9))
                    .add(jPanel24Layout.createSequentialGroup()
                        .add(jLabel28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jOznaka8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jStatus10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCenaNabavke2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jOznaka8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCenaNabavke2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jStatus10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel24Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jOznaka9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Uginula 25-09-2015", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 18), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel23.setForeground(new java.awt.Color(0, 0, 153));

        jOznaka7.setEditable(false);
        jOznaka7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jOznaka7.setForeground(new java.awt.Color(0, 0, 153));
        jOznaka7.setText("jTextField1");
        jOznaka7.setBorder(null);
        jOznaka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOznaka7ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setText("Razlog");

        org.jdesktop.layout.GroupLayout jPanel23Layout = new org.jdesktop.layout.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jOznaka7)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel23Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jOznaka7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Noteworthy", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Podatci o grlu");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setAlignmentY(3.0F);
        jLabel2.setMaximumSize(new java.awt.Dimension(219, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(219, 40));
        jLabel2.setPreferredSize(new java.awt.Dimension(219, 40));
        jLabel2.setSize(new java.awt.Dimension(40, 16));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPDFSnimiButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPDFSnimiButton.setText("Preuzmi PDF");
        jPDFSnimiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPDFSnimiButtonActionPerformed(evt);
            }
        });

        jOtkaziButton.setBackground(new java.awt.Color(0, 204, 255));
        jOtkaziButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jOtkaziButton.setText("Izadji");
        jOtkaziButton.setSelected(true);
        jOtkaziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOtkaziButtonActionPerformed(evt);
            }
        });

        jIzmeniButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jIzmeniButton.setText("Izmeni");
        jIzmeniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIzmeniButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelNabavka, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelOpstipodatci, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelRodjenje, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel25, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 410, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(12, 12, 12)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 55, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel24, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jIzmeniButton)
                                .add(18, 18, 18)
                                .add(jPDFSnimiButton)
                                .add(27, 27, 27)
                                .add(jOtkaziButton)
                                .add(9, 9, 9)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelOpstipodatci, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelRodjenje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelNabavka, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel25, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jIzmeniButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPDFSnimiButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jOtkaziButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 1, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 2, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jProcenatRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProcenatRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProcenatRActionPerformed

    private void jStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStatusActionPerformed

    private void jPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPolActionPerformed

    private void jOpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOpisActionPerformed

    private void jTezinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTezinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTezinaActionPerformed

    private void jLegloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLegloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLegloActionPerformed

    private void jMajkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMajkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMajkaActionPerformed

    private void jRodjenjeNapomenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRodjenjeNapomenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRodjenjeNapomenaActionPerformed

    private void jOtacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOtacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOtacActionPerformed

    private void jCenaNabavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCenaNabavkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCenaNabavkeActionPerformed

    private void jDetaljiNabavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDetaljiNabavkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDetaljiNabavkeActionPerformed

    private void jOznaka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOznaka7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOznaka7ActionPerformed

    private void jOznaka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOznaka8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOznaka8ActionPerformed

    private void jStatus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStatus10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStatus10ActionPerformed

    private void jOznaka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOznaka9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOznaka9ActionPerformed

    private void jLinijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLinijaActionPerformed

    private void jCenaNabavke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCenaNabavke1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCenaNabavke1ActionPerformed

    private void jTezina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTezina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTezina1ActionPerformed

    private void jCenaNabavke2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCenaNabavke2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCenaNabavke2ActionPerformed

    private void prepareForEdit(JTextField jtext){
        jtext.setEditable(true);
        jtext.setBorder(new AquaTextFieldBorder());
        jtext.setBackground(new Color(245,245,200));
    }
    private void disableEdit(JTextField jtext){
        jtext.setEditable(false);
        jtext.setBorder(null);
        jtext.setBackground(new Color(255,255,255));
    }    
    
    private void jIzmeniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIzmeniButtonActionPerformed
       jPol.setEnabled(true);
       jPol.setBackground(Color.yellow.brighter().brighter());
       prepareForEdit(jProcenatR);
       prepareForEdit(jLinija);
       prepareForEdit(jOpis);
       prepareForEdit(jTezina);
       jDosije.setEditable(true);
       jDosije.setBackground(new Color(245,245,200));
       
       jPDFSnimiButton.setText("Snimi izmene");
       jIzmeniButton.setEnabled(false);
       
    }//GEN-LAST:event_jIzmeniButtonActionPerformed

    private void jOtkaziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOtkaziButtonActionPerformed
        mainPanel.setLayout(new GridLayout());
        mainPanel.removeAll();
        mainPanel.add(new Podaci_ovaca(mainPanel, logic));
        mainPanel.revalidate();
        repaint();
    }//GEN-LAST:event_jOtkaziButtonActionPerformed

    private void azurirajOvcu(){
        pickOvcaFromForm();
        logic.updateOvca(ovca);
        mainPanel.removeAll();
        mainPanel.add(new OvcaPrikaz(mainPanel, logic, ovca));
        mainPanel.revalidate();
        repaint();
    }
    
    private void pickOvcaFromForm() {
        System.out.println("id "+ovca.getId());
        ovca.setProcenatR(jProcenatR.getText());
        ovca.setPol(jPol.getSelectedItem().toString().charAt(0));
        ovca.setOpis(jOpis.getText());
        ovca.setPracenje(jDosije.getText());
    }
    private void jPDFSnimiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPDFSnimiButtonActionPerformed
        if (jPDFSnimiButton.getText().equals("Preuzmi PDF")){
            
        } else {
            azurirajOvcu();        
        }
    }//GEN-LAST:event_jPDFSnimiButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jCenaNabavke;
    private javax.swing.JTextField jCenaNabavke1;
    private javax.swing.JTextField jCenaNabavke2;
    private javax.swing.JTextField jDetaljiNabavke;
    private javax.swing.JTextArea jDosije;
    private javax.swing.JButton jIzmeniButton;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jLeglo;
    private javax.swing.JTextField jLinija;
    private javax.swing.JTextField jMajka;
    private javax.swing.JTextField jOpis;
    private javax.swing.JTextField jOtac;
    private javax.swing.JButton jOtkaziButton;
    private javax.swing.JTextField jOznaka3;
    private javax.swing.JTextField jOznaka4;
    private javax.swing.JTextField jOznaka7;
    private javax.swing.JTextField jOznaka8;
    private javax.swing.JTextField jOznaka9;
    private javax.swing.JButton jPDFSnimiButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelNabavka;
    private javax.swing.JPanel jPanelOpstipodatci;
    private javax.swing.JPanel jPanelRodjenje;
    private javax.swing.JComboBox jPol;
    private javax.swing.JTextField jProcenatR;
    private javax.swing.JTextField jProcenatR2;
    private javax.swing.JTextField jRodjenjeNapomena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jStatus;
    private javax.swing.JTextField jStatus10;
    private javax.swing.JTextField jStatus4;
    private javax.swing.JTextField jStatus5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable15;
    private javax.swing.JTable jTable16;
    private javax.swing.JTable jTable17;
    private javax.swing.JTable jTable18;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTezina;
    private javax.swing.JTextField jTezina1;
    // End of variables declaration//GEN-END:variables


}
